name: restart

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # runs every 6 hours at minute 0

permissions:
  contents: read

jobs:
  restart:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: deployment check
        uses: github/branch-deploy@f0984057ffe1aa340aa017b6eafb894310aed88e # pin@v12.0.0
        id: deployment-check
        with:
          merge_deploy_mode: "true" # tells the Action to use the merge commit workflow strategy
          environment: production

      # always run checkout because the 'release (sentry)' step needs the code
      # do we still need this after removing sentry?
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          ref: ${{ steps.deployment-check.outputs.sha }}

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # pin@v7.0.0
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: install dependencies
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        run: npm install

      - name: register slash commands
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        env:
          NODE_ENV: ci
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        run: node deploy-commands.mjs

      - name: SSH Remote Deploy
        if: ${{ steps.deployment-check.outputs.continue == 'true' }}
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # pin@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: ~/stash/script/deploy -r "main" -d "/home/ubuntu/stash"
